version: '3.9'

networks:
  trans:

# Déclaration du volume ici
volumes:
  data:

services:
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                    DATABASE                         #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #

  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "5434:5434"
    networks:
      - trans
    volumes:
      - data:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}
    # volumes:
    #   - ./docker-data:/var/lib/postgresql/data
    
  # prisma:
  #   image: prismagraphql/prisma:1.34
  #   restart: always
  #   depends_on:
  #     back-end:
  #       condition: service_started
  #   ports:
  #     - '4466:4466'
  #   environment:
  #     PRISMA_CONFIG: |
  #       port: 4466
  #       managementApiSecret: mysecret42
  #       databases:
  #         default:
  #           connector: postgres
  #           host: database
  #           port: 5434
  #           user: postgresql
  #           password: pass


# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# #                   BACK-END                          #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  back-end:
    depends_on:
      database:
        condition: service_started
    networks:
      - trans
    build:
      context: ./back-end
      dockerfile: ../docker-data/back.dockerfile
    container_name: back-end
    image:  back-end
    environment:
      - FT_API_CLIENT_ID=${FT_API_CLIENT_ID}
      - FT_API_SECRET=${FT_API_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - HASH_SECRET=${HASH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - "./back-end:/app"
    restart: always


# # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                   FRONT-END                         #
# # # # # # # # # # # # # # # # # # # # # # # # # # # #
  front-end:
    depends_on:
     - database
     - back-end
    build:
      context: ./front-end
      dockerfile: ../docker-data/front.dockerfile
    container_name: front-end
    image: front-end
    ports:
      - "80:80"
    volumes:
      - ./front-end:/app
    networks:
      - trans
    restart: always
