version: "3.9"

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./postgres.env
    environment:
      TZ: "Europe/Paris"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5433:5433
    networks:
      - trans

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - ./pgadmin.env
    environment:
      TZ: "Europe/Paris"
    logging:
      driver: none
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    networks:
      - trans
    depends_on:
      - postgres

  # backend:
  #   build:
  #     context: ./docker
  #     dockerfile: ./backend.dockerfile
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - trans
  #   volumes:
  #     - ./backend:/app
  #   env_file:
  #     - ./docker/backend.env
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres

  # frontend:
  #   build:
  #     context: ./docker
  #     dockerfile: ./frontend.dockerfile
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - trans
  #   volumes:
  #     - ./frontend:/app
  #   env_file:
  #     - ./docker/frontend.env
  #   restart: unless-stopped
  #   depends_on:
  #     - backend

volumes:
  data:

networks:
  trans: